services:
  dns:
    image: ubuntu/bind9:9.16-20.04_edge
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - bind9:/etc/bind
      - $PWD/named.conf.local:/etc/bind/named.conf.local:ro
      - $PWD/named.conf.options:/etc/bind/named.conf.options:ro
    environment:
      - TZ=Europe/Zurich
volumes:
  bind9:
